### ISSUE TITLE
Autograd explanation video

### ISSUE THREAD

**Issue by PradeepSinghMakwana** [pytorch/tutorials#1024]
I found the tutorial on autograd from blitz a little hard to understand and I want to add  a video to it either at the end or start of the post. I want to get other's view on this. Thanks **Elliot Waite** for this awesome video [Video](https://youtu.be/MswxJw-8PvE)

**Comment by PradeepSinghMakwana** [comment]
[Here](https://github.com/pytorch/tutorials/pull/1025#issue-433617593) is my pull request

**Comment by elliotwaite** [comment]
@PradeepSinghMakwana, thanks for making this suggestion. It sounds like a good idea to me as long as the people running PyTorch also think it would be helpful for others.

I checked over your pull request and added one comment about possibly removing the "autoplay; " part in the HTML code so that it would conform with this previously added video code: https://github.com/pytorch/tutorials/commit/fb00d7827a7d7646390f6dc484684f303bd76789

Also, the failed Netlify checks look like they may be unrelated to this change. I would suggest trying to rerun the checks to see if you still get the same error message.

**Comment by PradeepSinghMakwana** [comment]
@elliotwaite Ya, thanks. Your suggestion was right. "autoplay; " was causing the problem.

**Comment by rogershijin** [comment]
I also thought this video was really helpful in my personal understanding of Autograd, wish I had seen it years earlier.

**Comment by zabboud** [comment]
@svekars What is missing from this issue - it seems like there were previous attempts for merging a PR - but is now out of date? 

@PradeepSinghMakwana what was the issue encountered?

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by elliotwaite** [comment]
Hi @svekars, thanks for checking in on this. I created a new PR for this issue here: https://github.com/pytorch/tutorials/pull/2625
