### ISSUE TITLE
Custom C++ and CUDA Extensions / multiple GPU issue

### ISSUE THREAD

**Issue by adam-ce** [pytorch/tutorials#1133]
Hi,
I followed the C++ extension tutorial (https://pytorch.org/tutorials/advanced/cpp_extension.html), but I had issues when using multiple GPUs.

The issue is solved: https://discuss.pytorch.org/t/c-cuda-extension-with-multiple-gpus/91241/6

I'd like to suggest adding the corresponding code lines to the tutorial, so that other people won't have the same problem.

Cheers, Adam

**Comment by holly1238** [comment]
See https://github.com/pytorch/pytorch/pull/48891 and https://github.com/pytorch/tutorials/issues/1196

**Comment by adam-ce** [comment]
I'm sorry, but I don't see the resolution of this issue.
- as far as i can see, the tutorial is unchanged (so to my understanding, #1196 is also not fixed)
- again, as far as i can see, pytorch/pytorch#48891 is about compilation, not memory errors during runtime.

cheers, Adam

**Comment by AlbertZhangHIT** [comment]
Hi, I also got the same issue for my custom C++ and CUDA extensions.

The `RuntimeError: CUDA error: an illegal memory access was encountered`  occurs especially when some other process is running some GPUs. Let's say, I have 2 GPUs and there is a network training process (PyTorch) running on GPU 0. If I run my custom CUDA extension by setting `device=torch.device('cuda:0')`, then the custom CUDA extension runs well while it slows down the other network training process. The CUDA error will occur if I set `device=torch.device('cuda:1')` for my custom CUDA extension. 

I found the solution from https://discuss.pytorch.org/t/c-cuda-extension-with-multiple-gpus/91241/6 does not work for the extension that the cpu extension and cuda extension are wrapped up by a common wrapper. Since the compilation of cpu extension will encounter the error that requires CUDA. Does anyone have idea about this issue?
