### ISSUE TITLE
DistributedDataParallel tutorial should use actual data

### ISSUE THREAD

**Issue by rmcavoy** [pytorch/tutorials#1237]
The current DistributedDataParallel tutorial feeds in data randomly generated on the spot. This is useful to a point but, since all real world applications will use a dataloader, it would be good to have a complete example with even MNIST that implements DistributedDataParallel. "https://pytorch.org/tutorials/intermediate/dist_tuto.html" implements the code required to use real data but also isn't using DistributedDataParallel thus leaving it up to the reader to determine which pieces they need to implement themselves and which pieces are included with DistributedDataParallel. Using real data and DistributedDataParallel would answer that question right away. One key question this would answer is how does the partitioning happen. Is the partitioning fully left to the user or is it handled by DistributedDataParallel like it is with DataParallel? I'm assuming the first one but it would be nice to have a clear example of it.

**Comment by svekars** [comment]
Since this issue was filled, we have published a [series of Distributed Training tutorials](https://pytorch.org/tutorials/distributed/home.html) which might already address this request. Please check them out and if  if there is anything you'd like to know about distributed training with PyTorch, file a new tutorial request. Thanks!
