### ISSUE TITLE
Translation tutorial

### ISSUE THREAD

**Issue by arogozhnikov** [pytorch/tutorials#127]
I find the implementation of EncoderRNN to be very strange when n_layers > 1.
See `forward` method below.

It applies the same GRU cell several times, so it is like doubling the sequence:
`word -> wwwooorrrddd`, but not adding new layers.

```python
class EncoderRNN(nn.Module):
    def __init__(self, input_size, hidden_size, n_layers=1):
        super(EncoderRNN, self).__init__()
        self.n_layers = n_layers
        self.hidden_size = hidden_size

        self.embedding = nn.Embedding(input_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size)

    def forward(self, input, hidden):
        embedded = self.embedding(input).view(1, 1, -1)
        output = embedded
        for i in range(self.n_layers):
            output, hidden = self.gru(output, hidden)
        return output, hidden

    def initHidden(self):
        <skipped>
```

**Comment by ozancaglayan** [comment]
I think it is not doubling but using the same GRU over and over on top of previously computed GRU states. I did not read the tutorial but It reminds me of a tied/shared RNN (where you reuse the parameters).

**Comment by arogozhnikov** [comment]
@ozancaglayan
yes, I've missed that. 

However, it is not weight tying, as it not only takes an output from the previous layer but also takes a hidden state. I have no idea why this can be useful.

-

**Comment by aa1607** [comment]
Any anwers on this? I thought the whole point of the stacked RNN was that you could apply it all in one go? If you want to apply more than one layer then why not just say : 'num_layers = 4' in the instantiation of self.gru? Is it possible that this was a mistake and the intention was to iterate over the timesteps rather than the layers? In an attention model that means you could collect up the hidden states and hand them over to the Attention layer..

**Comment by maye9999** [comment]
Same question about it. I think maybe it's a mistake?

**Comment by spro** [comment]
It is essentially weight sharing, there is one GRU layer with one set of weights. Using the new hidden state makes it work as if it was several layers, rather than repeating the letters as @arogozhnikov mentioned above (which would happen if you repeated the same hidden state inside the loop).

When I first implemented this it was a mistake, then I found that it actually converges faster than the "correct" way, but didn't explain that in the tutorial. However it is more standard to use the n_layers argument as in `nn.GRU(input_size, hidden_size, n_layers)` and that's what updated versions of the tutorial use.
