### ISSUE TITLE
Tut does not work

### ISSUE THREAD

**Issue by Arsmart123** [pytorch/tutorials#1828]
https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html
Here, pip install torch torchvision does not work, even can not compile with cuda
also, even use correct pytorch version, I can not see 'GPU' on my tensorboard.

**Comment by brianjo** [comment]
There is some information about enabling GPU from Colab here: https://colab.research.google.com/notebooks/gpu.ipynb Let me know if that helps. 

Also, the pip install isn't usually needed for Colab with PyTorch unless you need a specific version. In that case you would need a ! before the pip command in order to enable it.

**Comment by svekars** [comment]
Closing as the question seems to be answered. Feel free to reopen.
