### ISSUE TITLE
mistake in torchaudio data augmentation tutorial

### ISSUE THREAD

**Issue by Moadab-AI** [pytorch/tutorials#1930]
In the "adding background noise" section of the tutorial file : 
https://github.com/pytorch/tutorials/blob/master/beginner_source/audio_data_augmentation_tutorial.py

first of all you are calculating RMS but calling it power:
```
speech_power = speech.norm(p=2)
noise_power = noise.norm(p=2)
```
and then since you're dealing with RMS, the snr_db should be divided by 20 and not 10:
`snr = math.exp(snr_db / 10)`

also for a "standard" SNr value you'd have to use to log in base 10 as well i suppose.

**Comment by svekars** [comment]
@mthrok can you take a look?

**Comment by mthrok** [comment]
Hi @Moadab-AI 

Thanks for the issue. I think this has been fixed in torchaudio side https://github.com/pytorch/audio/pull/2285, and the change was ported in tutorial site in June.

Can you confirm that https://pytorch.org/tutorials/beginner/audio_data_augmentation_tutorial.html#adding-background-noise looks okay now?

Separately, I just realized that it has not been fixed on the next section;  https://pytorch.org/tutorials/beginner/audio_data_augmentation_tutorial.html#simulating-a-phone-recoding

**Comment by svekars** [comment]
This tutorial was moved. If this is still an issue, please raise in the pytorch/audio repo.
