### ISSUE TITLE
Mentioning Torch/Torchvision version in Tutorials

### ISSUE THREAD

**Issue by InnovArul** [pytorch/tutorials#1946]
Recently I came across some queries in the Pytorch forum about the Torchvision object detection tutorial.

https://discuss.pytorch.org/t/transforms-helper-function-has-no-attribute-totensor/153985
https://discuss.pytorch.org/t/change-mask-in-randomhorizontalflip-transform/154091

The basic issue is that the tutorial was created with an older version of the Torchvision package and the version number is not mentioned in the tutorials. (the version number is mentioned in the Colab notebook though)

What would be a better solution?

1) The tutorials may be updated to consider latest torchvision package
2) The torch/torchvision version numbers could be mentioned explicitly in the tutorials

**Comment by svekars** [comment]
@datumbox @fmassa any thoughts on the above?

**Comment by datumbox** [comment]
Thanks for bringing it to our attention. We are trying to phase out the `ToTensor` idiom (still supported but not promoted via our examples) because the method does too many things (convert to tensor + scale input). When we made the change we missed the tutorial, so I issued a PR to fix it at #1994.

@svekars Would you be able to help me review and merge?
