### ISSUE TITLE
Runtime error @ quickstart_tutorial.py

### ISSUE THREAD

**Issue by VikasChidananda** [pytorch/tutorials#1983]
https://github.com/pytorch/tutorials/blob/master/beginner_source/basics/quickstart_tutorial.py

I get a runtime error when using *model.eval()* on cuda

* model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')  *

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)

I could solve this by changing: 
        pred = model(x.to(device))

**Comment by suraj813** [comment]
@VikasChidananda thank you for bringing this up! This runtime error should not be raised if you run every line in that script; are you running into this error because [L212](https://github.com/pytorch/tutorials/blob/db34a779242f1a71346db4a9e5d6ac962a8d9b77/beginner_source/basics/quickstart_tutorial.py#L212) was not run before the evaluation code? 

However, it is good practice to move the model and inputs (`x,y`) to `device`, especially since we have defined that at the top of the script. Would you like to raise a PR to update L212 and L232 so that the model and x,y are on `device`?
