### ISSUE TITLE
The search is broken on the tutorials site

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2015]
One of the recent PRs broke search on the tutorials website: https://pytorch.org/tutorials/ 

cc: @malfet

**Comment by malfet** [comment]
This is caused by uncaught exception in searchtool.js:
```
jquery.js:2 Uncaught TypeError: _ is not a function
    at Object.performSearch (searchtools.js:400:29)
```

**Comment by malfet** [comment]
Commit https://github.com/pytorch/tutorials/commit/2dce5ce914bcde316e1a10c784ab7fdc9667236f broke it, but it worked on https://github.com/pytorch/tutorials/commit/41a76db31ea080bb406de8f88d64b35363fd433c

**Comment by malfet** [comment]
Some updates: [tutorials/_static/searchtools.js](https://github.com/pytorch/tutorials/blob/d4eab8acb415c41873b247c4c693e8d239c67410/_static/searchtools.js) were added 4+ years ago by https://github.com/pytorch/tutorials/commit/963265fcce89818c8eaee7f6354993eef387fdab and appears to be a verbatim copy of https://github.com/sphinx-doc/sphinx/blob/v1.8.2/sphinx/themes/basic/static/doctools.js

After updating it to a version from sphinx-5.1.1 the issue is gone, which leaves 2 questions unanswered:
- Why do we have those checked into turorials repo rather than automatically copied over from respective sphinx version
- What would be the easiest way of adding test to detect those types of regressions in the future
