### ISSUE TITLE
Quantize weights to unisgned 8 bit

### ISSUE THREAD

**Issue by rohanjuneja** [pytorch/tutorials#2151]
I am trying to quantize the weights of the BERT model to unsigned 8 bits. Am using the 'dynamic_quantize' function for the same.

`quantized_model = torch.quantization.quantize_dynamic(
    model, {torch.nn.Linear}, dtype=torch.quint8
)`

But it throws the error 'AssertionError: The only supported dtypes for dynamic quantized linear are qint8 and float16 got: torch.quint8'.

Is there any specific reason for this not to be supported? Could I use any other method to quantize the weights to unsigned int8 bits?

Here is a link to the colab sheet:
https://colab.research.google.com/drive/14G_jdLuZD5846jUDZUdGNf1x0DMz8GKK?usp=sharing

Thanks!

cc @jerryzh168 @z-a-f @vkuzo

**Comment by z-a-f** [comment]
That's because `ao.nn.quantized.dynamic.Linear` only supports `QINT8`. Notice the [default config in the dynamic quant](https://pytorch.org/docs/stable/_modules/torch/ao/quantization/quantize.html#quantize_dynamic) falls back to the `torch.qint8`. Also, you might have noticed that the assertion is hard-coded in the [`quantized/dynamic/linear.py`](https://github.com/pytorch/pytorch/blob/c887837ec30e88a0a1181e7e371e6437050402c5/torch/ao/nn/quantized/dynamic/modules/linear.py#L107-L108). That's because there are no `uint8` implementations for the linear ([see here](https://github.com/pytorch/pytorch/blob/c887837ec30e88a0a1181e7e371e6437050402c5/aten/src/ATen/native/quantized/cpu/qlinear_dynamic.cpp#L664-L678)).

Is there a reason for it to be `uint8`? Functionally it's the same as the `int8`.
