### ISSUE TITLE
💡 [REQUEST] - How to use TorchServe on Vertex

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2346]
### 🚀 Descirbe the improvement or the new tutorial

Create a tutorial on how to use TorchServe on Vertex AI

cc @msaroufim @agunapal @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by HemanthSai7** [comment]
I want to take up this issue, but Torchserve docs has a link to a Google blogpost for the tutorial.

**Comment by Ilinapradhan** [comment]
\assigntome

**Comment by viveks-codes** [comment]
@Ilinapradhan You need to use / . I am working on this issue ; )

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by spzala** [comment]
@svekars I will try to create the initial tutorial page based on my understanding of what's needed here. I am not sure about it but thinking to try it seeing the issue was unassigned multiple times and no one's working on it currently. If my first quick PR doesn't make sense, I will free up the issue :). Also, I want to make sure if we can really do this tutorial because the use of Vertex AI is billable so I think it's something we can't test. Thanks!
