### ISSUE TITLE
Multiple GPU example limited to one GPU

### ISSUE THREAD

**Issue by 9cpluss** [pytorch/tutorials#2563]
https://github.com/pytorch/tutorials/blob/646c8b6368e4f43acc808e0ddddc569153d6a30f/beginner_source/blitz/data_parallel_tutorial.py#L60

Isn't this line limiting the example to **one** GPU no matter how many GPUs are available?

cc @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by svekars** [comment]
Yes, if index is removed, it will be multiple GPU: 
```device = torch.device("cuda" if torch.cuda.is_available() else "cpu")```

**Comment by malfet** [comment]
> Yes, if index is removed, it will be multiple GPU: `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`

Sorry, can you point me to some sort of documentation that confirms that? Key component of the tutorial is use of [`nn.DataParallel`](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html), which puts them on mutliple GPUs, index of the device is irrelevant afterwards, as long as model is running on GPU. One can control how many GPUs are used  by passing `device_ids` to `nn.DataParallel` constructor, otherwise all available ones will be used all the time.

**Comment by svekars** [comment]
Yes, you're right, then I guess we can just close this one.
