### ISSUE TITLE
[BUG] - UserWarning:  Using torch.cross without specifying the dim arg is deprecated.

### ISSUE THREAD

**Issue by njzjz** [pytorch/tutorials#2933]
### Add Link

https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

### Describe the bug

![image](https://github.com/pytorch/tutorials/assets/9496702/e7140c3b-6917-43b8-8430-2097174a3c19)

```
/var/lib/workspace/beginner_source/introyt/tensors_deeper_tutorial.py:462: UserWarning:

Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:62.)
```

### Describe your environment

I don't actually run it but find the web page has such a warning.

**Comment by ignaciobartol** [comment]
Hi, after checking on this bug, there are a few things that I noted here:
1. While `torch.cross` is more flexible and allows you for more complex cross products, I believe the expected behavior is usually the one from `torch.linalg.cross` implementation. In [this discussion](https://github.com/pytorch/pytorch/issues/62810) it explains why *blindly* using `torch.cross` can lead you to an intersting bug-hunting. 
2. The function `torch.svd` is deprecated and will be removed in future pytorch release. 

I am submitting a PR to attempt to solve this issue and updating the tutorial.
