### ISSUE TITLE
AttributeError: Use of outdated functions in the tutorial 

### ISSUE THREAD

**Issue by glitch401** [pytorch/tutorials#536]
The tutorial of Pytorch is quite a savy tool to get started, but  is confusing from the begining as it runs perfectly on Google Colab, while you get errors like 

> AttributeError: module 'torch' has no attribute 'empty'

from the very first line of the tutorial code:
`x = torch.empty(5,3)`
`print(x)`

**Comment by jlin27** [comment]
Hi @glitch401 - Thanks for the feedback. That error seems to be because there was an issue with how torch.empty is initialized as Richard discusses in this post: https://discuss.pytorch.org/t/torch-empty-doesnt-work/17147/5

That issue should be fixed now. If it's not for you, can you let us know what version of PyTorch you are using?
