### ISSUE TITLE
unused hidden variables of LSTM on deep_learning_nlp_tutorial.py examples

### ISSUE THREAD

**Issue by antran89** [pytorch/tutorials#55]
Hi,

I am just curious about line [1197](https://github.com/pytorch/tutorials/blob/master/beginner_source/deep_learning_nlp_tutorial.py#L1197). 
```
self.hidden = self.init_hidden()
```

This value has not been used to update parameters of network in the program. But you are saying `also, we need to clear out the hidden state of the LSTM, detaching it from its history on the last instance`. Is it correct?

Best regards,

**Comment by chsasank** [comment]
@rguthrie3, would you mind answering the above?

PS: After reorganisation of tutorial, part with this code is [here](http://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html)

**Comment by Varal7** [comment]
I believe this is due to a typo in line 178.

As we can see in Pytorch's [code](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L61), the `nn.lstm` model's arguments  `(h0, c_0)` are optional. 
If no arguments are passed, then the model creates a hidden state and cell state based on input.

In this case, we want our hidden state to be passed to the next iteration. Hence, #63.

**Comment by antran89** [comment]
@Varal7 Thank for clarification.

**Comment by rguthrie3** [comment]
I fixed this bug in my version of the repo, but I think that the version in this repo was copied over before I fixed that bug. the call to the lstm should take the self.hidden state as an argument, and update the hidden state after each call.
