### ISSUE TITLE
Inference time of quantized model is longer than normal model

### ISSUE THREAD

**Issue by shivamsaboo17** [pytorch/tutorials#691]
In the tutorial for model quantization, the time taken for quantized model is longer than normal model. Am I missing something? Adding screenshot:
![Screenshot_20191011-010601](https://user-images.githubusercontent.com/23507911/66601147-d586a800-ebc4-11e9-9cdb-929a0f75977d.png)

**Comment by chuanhuayang** [comment]
I got the similar result too, in the tutorials, a detail discribed like this "Note: we number of threads to one for single threaded comparison, since quantized models run single threaded."
if i add "torch.set_num_threads(1)", the quantized model is better
if deleted this setting, the normal is better， i think the quantized would not use parallel cpu core.
